import indianMuseumImg from '../../app/assets/popularMuseums/tim.jpg';
import nationalMuseumImg from '../../app/assets/popularMuseums/nm.png'; // Updated to png
import chhatrapatiShivajiImg from '../../app/assets/popularMuseums/csm.png'; // Updated to png
import rajaDinkarKelkarImg from '../../app/assets/popularMuseums/rd.jpg'; // Updated to png
import salarJungImg from '../../app/assets/popularMuseums/sjm.jpg';
import mysoreZooImg from '../../app/assets/popularMuseums/mysuruzm.png';
import victoriaMemorialImg from '../../app/assets/popularMuseums/vmk.jpeg';

export const data = [
    {
      id: 1,
      name: "The Indian Museum",
      category: "Historical",
      established: "Established in 1814",
      address: "Kolkata, West Bengal",
      image: indianMuseumImg,
    },
    {
      id: 2,
      name: "National Museum",
      category: "Archaeological",
      established: "Established in 1949",
      address: "New Delhi, Delhi",
      image: nationalMuseumImg,
    },
    {
      id: 3,
      name: "Chhatrapati Shivaji Maharaj Vastu Sangrahalaya",
      category: "Art",
      established: "Established in 1922",
      address: "Mumbai, Maharashtra",
      image: chhatrapatiShivajiImg,
    },
    {
      id: 4,
      name: "Raja Dinkar Kelkar Museum",
      category: "Cultural",
      established: "Established in 1962",
      address: "Pune, Maharashtra",
      image: rajaDinkarKelkarImg,
    },
    {
      id: 5,
      name: "Salar Jung Museum",
      category: "Historical",
      established: "Established in 1951",
      address: "Hyderabad, Telangana",
      image: salarJungImg,
    },
    {
      id: 6,
      name: "Mysore Zoo and Museum",
      category: "Natural History",
      established: "Established in 1892",
      address: "Mysore, Karnataka",
      image: mysoreZooImg,
    },
    {
      id: 7,
      name: "Victoria Memorial",
      category: "Art",
      established: "Established in 1921",
      address: "Kolkata, West Bengal",
      image: victoriaMemorialImg,
    },
    {
      id: 8,
      name: "Government Museum, Chennai",
      category: "Historical",
      established: "Established in 1851",
      address: "Chennai, Tamil Nadu",
      image: mysoreZooImg,
    },
    {
      id: 9,
      name: "Bharat Kala Bhavan Museum",
      category: "Cultural",
      established: "Established in 1920",
      address: "Varanasi, Uttar Pradesh",
      image: mysoreZooImg,
    },
    {
      id: 10,
      name: "Albert Hall Museum",
      category: "Art",
      established: "Established in 1887",
      address: "Jaipur, Rajasthan",
      image: mysoreZooImg,
    },
    {
      id: 11,
      name: "Shankar's International Dolls Museum",
      category: "Cultural",
      established: "Established in 1965",
      address: "New Delhi, Delhi",
      image: mysoreZooImg,
    },
    {
      id: 12,
      name: "Calico Museum of Textiles",
      category: "Cultural",
      established: "Established in 1949",
      address: "Ahmedabad, Gujarat",
      image: mysoreZooImg,
    },
    {
      id: 13,
      name: "Prince of Wales Museum",
      category: "Art",
      established: "Established in 1922",
      address: "Mumbai, Maharashtra",
      image: mysoreZooImg,
    },
    {
      id: 14,
      name: "Visvesvaraya Industrial and Technological Museum",
      category: "Science",
      established: "Established in 1962",
      address: "Bengaluru, Karnataka",
      image: mysoreZooImg,
    },
    {
      id: 15,
      name: "Indira Gandhi Rashtriya Manav Sangrahalaya",
      category: "Anthropology",
      established: "Established in 1977",
      address: "Bhopal, Madhya Pradesh",
      image: mysoreZooImg,
    },
    {
      id: 16,
      name: "Napier Museum",
      category: "Archaeological",
      established: "Established in 1855",
      address: "Thiruvananthapuram, Kerala",
      image: mysoreZooImg,
    },
    {
      id: 17,
      name: "Birla Industrial and Technological Museum",
      category: "Science",
      established: "Established in 1959",
      address: "Kolkata, West Bengal",
      image: mysoreZooImg,
    },
    {
      id: 18,
      name: "Indian Air Force Museum",
      category: "Military",
      established: "Established in 1967",
      address: "New Delhi, Delhi",
      image: mysoreZooImg,
    },
    {
      id: 19,
      name: "Gandhi Smriti",
      category: "Historical",
      established: "Established in 1955",
      address: "New Delhi, Delhi",
      image: mysoreZooImg,
    },
    {
      id: 20,
      name: "National Rail Museum",
      category: "Transport",
      established: "Established in 1977",
      address: "New Delhi, Delhi",
      image: mysoreZooImg,
    }
  ];
  